name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run basic import test
      run: |
        python -c "import torch; print(torch.__version__)"
        python -c "import PIL; print(PIL.__version__)"
    
    - name: Create test reports directory
      run: |
        mkdir -p test-reports
        
    - name: Run tests
      run: |
        pytest tests/ -v --junitxml=test-reports/junit.xml --cov=./ --cov-report=xml || true